export const dummyEntries = () => {
  return [
    {
      id: 0,
      date: new Date('2024-04-01 GMT-7'),
      description: 'Rent',
      category: 'Monthly',
      value: -2000,
    },
    {
      id: 1,
      date: new Date('2024-04-04 GMT-7'),
      description: 'Paycheck',
      category: 'Paycheck',
      value: 4000,
    },
    {
      id: 2,
      date: new Date('2024-04-06 GMT-7'),
      description: 'Walmart',
      category: 'Groceries',
      value: -800,
    },
    {
      id: 3,
      date: new Date('2024-04-10 GMT-7'),
      description: 'Docks Fish and Chips',
      category: 'Other',
      value: -36.20,
    },
    {
      id: 4,
      date: new Date('2024-04-17 GMT-7'),
      description: 'Compass',
      category: 'Monthly',
      value: -180.0,
    },
    {
      id: 5,
      date: new Date('2024-04-29 GMT-7'),
      description: 'Superstore',
      category: 'Groceries',
      value: -60.92,
    },
    {
      id: 6,
      date: new Date('2024-05-01 GMT-7'),
      description: 'Rent',
      category: 'Monthly',
      value: -2000.0,
    },
    {
      id: 7,
      date: new Date('2024-05-06 GMT-7'),
      description: 'Paycheck',
      category: 'Paycheck',
      value: 4000,
    },
    {
      id: 8,
      date: new Date('2024-05-10 GMT-7'),
      description: 'Compass',
      category: 'Monthly',
      value: -180.0,
    },
    {
      id: 9,
      date: new Date('2024-05-12 GMT-7'),
      description: 'Walmart',
      category: 'Groceries',
      value: -890.47,
    },
    {
      id: 10,
      date: new Date('2024-05-16 GMT-7'),
      description: 'Netflix',
      category: 'Monthly',
      value: -6.99,
    },
    {
      id: 11,
      date: new Date('2024-05-17 GMT-7'),
      description: 'Amazon',
      category: 'Other',
      value: -210.0,
    },
    {
      id: 12,
      date: new Date('2024-06-01 GMT-7'),
      description: 'Rent',
      category: 'Monthly',
      value: -2000.0,
    },
    {
      id: 13,
      date: new Date('2024-06-05 GMT-7'),
      description: 'Paycheck',
      category: 'Paycheck',
      value: 4000,
    },
    {
      id: 14,
      date: new Date('2024-06-14 GMT-7'),
      description: 'PS5 game',
      category: 'Other',
      value: -69.90,
    },
    {
      id: 15,
      date: new Date('2024-06-16 GMT-7'),
      description: 'Netflix',
      category: 'Monthly',
      value: -6.99,
    },
    {
      id: 16,
      date: new Date('2024-06-20 GMT-7'),
      description: 'Compass',
      category: 'Monthly',
      value: -180.0,
    },
    {
      id: 17,
      date: new Date('2024-06-22 GMT-7'),
      description: 'Save On',
      category: 'Groceries',
      value: -250.0,
    },
  ];
};
